/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Class.Peminjaman;
import Koneksi.Koneksi;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PeminjamanUI extends javax.swing.JPanel {

    /**
     * Creates new form PeminjamanUI
     */
    public PeminjamanUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        idPeminjamPinjamField = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenisMobilComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tanggalComboBox = new javax.swing.JComboBox<>();
        bulanComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lamaPinjamField = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        biayaPinjamField = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        totalPinjamField = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        kembaliPinjamField = new javax.swing.JTextPane();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tahunPinjamField = new javax.swing.JTextField();
        idpegawaiComboBox = new javax.swing.JComboBox<>();
        idpelangganComboBox = new javax.swing.JComboBox<>();
        todayButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(190, 197, 173));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 126, 83));
        jLabel1.setText("Transaksi Peminjaman");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id Pegawai :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Id Peminjaman :");

        jScrollPane2.setViewportView(idPeminjamPinjamField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Id Pelanggan :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Mobil :");

        jenisMobilComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jenisMobilComboBoxFocusGained(evt);
            }
        });
        jenisMobilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisMobilComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam :");

        tanggalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tgl", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tanggalComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tanggalComboBoxFocusGained(evt);
            }
        });
        tanggalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalComboBoxActionPerformed(evt);
            }
        });

        bulanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bln", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        bulanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Hari");

        jScrollPane5.setViewportView(lamaPinjamField);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Lama Pinjam :");

        generateButton.setText("GENERATE");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Biaya Sewa :");

        jScrollPane6.setViewportView(biayaPinjamField);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Per Hari");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Total Sewa :");

        jScrollPane7.setViewportView(totalPinjamField);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal Kembali :");

        jScrollPane8.setViewportView(kembaliPinjamField);

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        tahunPinjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunPinjamFieldActionPerformed(evt);
            }
        });

        idpegawaiComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idpegawaiComboBoxFocusGained(evt);
            }
        });

        idpelangganComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idpelangganComboBoxFocusGained(evt);
            }
        });

        todayButton.setText("Hari ini");
        todayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idpegawaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jenisMobilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10))
                                        .addComponent(jScrollPane7)
                                        .addComponent(jScrollPane8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tanggalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tahunPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(todayButton)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idpelangganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idpegawaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idpelangganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jenisMobilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tanggalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todayButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jenisMobilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisMobilComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisMobilComboBoxActionPerformed

    private void tanggalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalComboBoxActionPerformed

    private void bulanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanComboBoxActionPerformed

    private void disabledField() {
        idpegawaiComboBox.setSelectedIndex(-1);
        idPeminjamPinjamField.setText(null) ;
        idpelangganComboBox.setSelectedIndex(-1);
        jenisMobilComboBox.setSelectedIndex(-1);
        tanggalComboBox.setSelectedIndex(0);
        bulanComboBox.setSelectedIndex(0); 
        tahunPinjamField.setText(null); 
        kembaliPinjamField.setText(null); 
        lamaPinjamField.setText(null); 
        biayaPinjamField.setText(null);
        totalPinjamField.setText(null) ;
    }
    
    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try {
          rs = kon.getData("select * from mobil where jenis_mobil = \'" + jenisMobilComboBox.getSelectedItem() + "\'");
          while (rs.next()) {
            biayaPinjamField.setText(rs.getString("sewa_mobil"));
            int k, l, m, n, o;
            k = Integer.valueOf(lamaPinjamField.getText());
            l = Integer.valueOf("" + tanggalComboBox.getSelectedItem());
            n = Integer.valueOf(biayaPinjamField.getText());
            m = k + l;
            o = k * n ;
            totalPinjamField.setText(String.valueOf(o));
            kembaliPinjamField.setText(String.valueOf(m) + "/" + bulanComboBox.getSelectedItem() + "/" + tahunPinjamField.getText());
          }
          rs.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Peminjaman pem = new Peminjaman();
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        String id_mobil = "";
        int stok = 0;
        
        try{
            rs = kon.getData("select * from mobil where jenis_mobil=\'" + jenisMobilComboBox.getSelectedItem() + "\'");
            while (rs.next()) {
                id_mobil = rs.getString("id_mobil");
                stok = Integer.valueOf(rs.getString("stok_mobil"));
                stok--;
            }
            kon.query("UPDATE mobil SET stok_mobil = \'" + stok + "\'WHERE id_mobil=\'" + id_mobil + "\'");
            rs.close();
        } catch (Exception e){
            
        }
        
        pem.setPeminjaman(idPeminjamPinjamField.getText());
        pem.setPelanggan("" + idpelangganComboBox.getSelectedItem());
        
        pem.setMobil("" + id_mobil);
        pem.setPtanggal("" + tanggalComboBox.getSelectedItem());
        pem.setPbulan("" + bulanComboBox.getSelectedItem());
        pem.setPtahun(tahunPinjamField.getText());
        pem.setKtahun(kembaliPinjamField.getText());
        pem.setLama(lamaPinjamField.getText());
        pem.setPetugas("" + idpegawaiComboBox.getSelectedItem());
        pem.setBiaya(biayaPinjamField.getText());
        pem.insertPeminjaman();
        JOptionPane.showMessageDialog(null, "Insert Berhasil");
        disabledField();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void tahunPinjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunPinjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunPinjamFieldActionPerformed

    private void jenisMobilComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisMobilComboBoxFocusGained
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        jenisMobilComboBox.removeAllItems();
        int i = 0;
        try {
          rs = kon.getData("select * from mobil where stok_mobil > 0");
          while (rs.next()) {
            jenisMobilComboBox.addItem(rs.getString("jenis_mobil"));
            i++;
          }
          rs.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_jenisMobilComboBoxFocusGained

    private void tanggalComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalComboBoxFocusGained
        
    }//GEN-LAST:event_tanggalComboBoxFocusGained

    private void idpegawaiComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idpegawaiComboBoxFocusGained
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        idpegawaiComboBox.removeAllItems();
        int i = 0;
        try {
          rs = kon.getData("select * from pegawai");
          while (rs.next()) {
            idpegawaiComboBox.addItem(rs.getString("id_pegawai"));
            i++;
          }
          rs.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_idpegawaiComboBoxFocusGained

    private void idpelangganComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idpelangganComboBoxFocusGained
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        idpelangganComboBox.removeAllItems();
        int i = 0;
        try {
          rs = kon.getData("select * from pelanggan");
          while (rs.next()) {
            idpelangganComboBox.addItem(rs.getString("id_pelanggan"));
            i++;
          }
          rs.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_idpelangganComboBoxFocusGained

    private void todayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayButtonActionPerformed
        LocalDateTime currTime = LocalDateTime.now();
        
        tanggalComboBox.setSelectedIndex(currTime.getDayOfMonth());
        bulanComboBox.setSelectedIndex(currTime.getMonthValue());
        tahunPinjamField.setText(String.valueOf(currTime.getYear()));
    }//GEN-LAST:event_todayButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        disabledField();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane biayaPinjamField;
    private javax.swing.JComboBox<String> bulanComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextPane idPeminjamPinjamField;
    private javax.swing.JComboBox<String> idpegawaiComboBox;
    private javax.swing.JComboBox<String> idpelangganComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JComboBox<String> jenisMobilComboBox;
    private javax.swing.JTextPane kembaliPinjamField;
    private javax.swing.JTextPane lamaPinjamField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tahunPinjamField;
    private javax.swing.JComboBox<String> tanggalComboBox;
    private javax.swing.JButton todayButton;
    private javax.swing.JTextPane totalPinjamField;
    // End of variables declaration//GEN-END:variables
}
